# -*- mode: ruby -*-
# vi: set ft=ruby :

$NODES=3
$NODEMEM=1024
# Overwrite host locale in ssh session
ENV["LC_ALL"] = "en_US.UTF-8"

# All Vagrant configuration is done here.
Vagrant.configure("2") do |cluster|
  # The most common configuration options are documented and commented below.
  # For more refer to https://www.vagrantup.com/docs/vagrantfile/

  # Every Vagrant virtual environment requires a box to build off of.

  # The ordering of these 2 lines expresses a preference for a hypervisor
  cluster.vm.provider "virtualbox"

  # Avoid using the Virtualbox guest additions
  cluster.vm.synced_folder ".", "/vagrant", disabled: true
  if Vagrant.has_plugin?("vagrant-vbguest")
    cluster.vbguest.auto_update = false
  end

  cluster.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
  cluster.vm.provision "shell", inline: "cat ~vagrant/.ssh/me.pub >> ~vagrant/.ssh/authorized_keys"

  # For convenience, testing and instruction, all you need is 'vagrant up'

  # host to run ansible and tower
  cluster.vm.define "ansible", primary: true do |config|
    config.vm.hostname = "ansible"
    config.vm.network :private_network, ip: "10.42.0.2"
    config.vm.provider :virtualbox do |vb, override|
      # This vagrant box is downloaded from https://vagrantcloud.com/centos/7
      # Other variants https://app.vagrantup.com/boxes/search
      override.vm.box = "centos/7"

      vb.customize [
        "modifyvm", :id,
        "--name", "ansible",
        "--memory", "2048",
        "--cpus", 1
      ]
    end
  end

  # hosts to run ansible-core
  (1..$NODES).each do |i|
    cluster.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      node.vm.network :private_network, ip: "10.42.0.#{i+5}"
      node.vm.provider :virtualbox do |vb, override|
        override.vm.box = "centos/7"

        vb.customize [
          "modifyvm", :id,
          "--name", "node-#{i}",
          "--memory", "#$NODEMEM",
          "--cpus", 1
        ]
      end
    end
  end
end
