---
  
- hosts:
    - "tag_identity_git"
    - "tag_identity_tower"
    - "tag_identity_system"
  connection: "local"
  gather_facts: false
  vars_files:
    - vars/vars.yml

  tasks:
  - name: "Remove tagged EC2 instances from security group"
    ec2:
      state: "running"
      region: "{{ ec2_region }}"
      instance_ids: "{{ ec2_id }}"
      group_id: ""
    delegate_to: "localhost"

  - name: "Terminate tagged EC2 instances"
    ec2:
      state: "absent"
      region: "{{ ec2_region }}"
      instance_ids: "{{ ec2_id }}"
      wait: true
    delegate_to: "localhost"


- hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars_files:
    - vars/vars.yml
  tasks:
  - name: "Remove security group for tower"
    ec2_group:
      name: "{{ ec2_security_group_tower }}"
      region: "{{ ec2_region }}"
      state: "absent"

  - name: "Remove security group for clients"
    ec2_group:
      name: "{{ ec2_security_group_client_systems }}"
      region: "{{ ec2_region }}"
      state: "absent"

  - name: "Remove security group for gitlab"
    ec2_group:
      name: "{{ ec2_security_group_gitlab }}"
      region: "{{ ec2_region }}"
      state: "absent"
